apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: hirefy
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "change-me"
  MYSQL_DATABASE: "hirefy"
  MYSQL_USER: "hirefy"
  MYSQL_PASSWORD: "change-me-too"