apiVersion: v1
kind: Secret
metadata:
  name: quiz-service-secret
  namespace: hirefy
type: Opaque
stringData:
  DATABASE_URL: "mysql://hirefy:change-me-too@mariadb:3306/hirefy"
---
apiVersion: apps/v1
kind: Deployement
metadata:
  name: quiz-service
  namespace: hirefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: quiz-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: quiz-service-secret
                  key: DATABASE_URL
--- 
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: hirefy
spec:
  selector:
    app: quiz-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP