apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: hirefy
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    ui = true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: hirefy
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: hirefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
            - name: SKIP_SETCAP
              value: "true"
          command: ["vault", "server", "-config=/vault/config/vault.hcl"]
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mounthhPath: /vault/data
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: config
          configMap:
            name: vault-config
        - name: data
          persistentVolumeClaim:
            claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: hirefy
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  type: ClusterIP
  
