apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hirefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: front-service-config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: VITE_API_URL # to check
              value: "http://gateway:8081" #put it in env token
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hirefy
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-service-config
  namespace: hirefy
data:
  VITE_MAIN_SERVICE_URL: "http://13.36.189.126/api/main/"
  VITE_CHAT_SERVICE_URL: "http://13.36.189.126/api/main/"
  VITE_QUIZ_SERVICE_URL: "http://13.36.189.126/api/quiz/"
  VITE_MAIN_API_URL: "/api/main"
  VITE_QUIZ_API_URL: "/api/quiz"
