ui:
  enabled: true

injector:
  enabled: true
server:
  dev:
    enabled: true
    devRootToken: "root" # Put it in env var
  enabled: true
  replicas: 1
  
  # dataStorage:
  #   enabled: true
  #   size: 1Gi
  #   mountPath: /vault/data 
  
  standalone:
    enabled: true
  
  extraEnvironmentVars:
    VAULT_ADDR: "http://127.0.0.1:8200" # put it in env var