
import { useState, useEffect } from 'react';


export function OTPpage(){

    const OTP = () => {
        return(
            <div className="p-1 flex flex-col w-full h-full gap-10 items-center my-4">
                <div className='flex flex-col gap-1 items-center '>
                    <h1 className='font-bold text-white text-2xl'>Authentication</h1>
                    <h1 className='font-light text-white text-lg'>Enter the code generated by your Authentication App</h1>
                </div>
                <div className='h-full w-full flex flex-col gap-10'>
                    <div className='Inputs flex justify-between '>
                        <input type="text" 
                            className='h-20 w-16 border border-[#5F88B8]  rounded-lg outline-none'/>
                        <input type="text" 
                            className='h-20 w-16 border border-[#5F88B8]  rounded-lg outline-none'/>
                        <input type="text" 
                            className='h-20 w-16 border border-[#5F88B8]  rounded-lg outline-none'/>
                        <input type="text" 
                            className='h-20 w-16 border border-[#5F88B8]  rounded-lg outline-none'/>
                        <input type="text" 
                            className='h-20 w-16 border border-[#5F88B8]  rounded-lg outline-none'/>
                        <input type="text" 
                            className='h-20 w-16 border border-[#5F88B8]  rounded-lg outline-none'/>
                    </div>
                    <button className='w-full h-14 bg-[#44BC19] rounded-lg text-white'>Verify account</button>
                </div>
            </div>
        );
    }
  
    
    return(
        <div className={`h-[600px] w-full sm:p-5 sm:w-[500px] p-0 border border-[#5F88B8]  rounded bg-[#09122C] mx-auto flex items-center justify-center overflow-hidden`}>
            <div className="flex-grow  h-full w-full">
                {<OTP />}
            </div>
        </div>
        
    );
}