

spring:
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: http://main-service
          predicates:
            - Path=/api/main/**
        - id: quiz-service
          uri: http://quiz-service
          predicates:
            - Path=/api/quiz/**
        - id: ai-service
          uri: http://ai-service
          predicates:
            - Path=/api/ai/**