server_tokens off;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server 
{
    listen 8080 default_server;

    server_name localhost;

    modsecurity on;
    # modsecurity_rules_file /etc/nginx/modsecurity.d/modsecurity.conf;
    
    set $upstream ${BACKEND};
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        include includes/cors.conf;
        include includes/proxy_backend.conf;
    }

    include includes/location_common.conf;
}