events {}

client_max_body_size 2M;
http {
    server 
    {
        listen 80;

        location / {
            proxy_pass http://api-gateway:8081;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}