
server_tokens off;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server 
{
    listen 8080 default_server;
    server_name localhost;
    
    modsecurity on;

    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s; 
    client_max_body_size 50M;
    # Dynamic DNS resolution for Kubernetes services
    resolver 10.43.0.10 valid=10s;
    set $upstream_frontend "http://frontend.hirefy.svc.cluster.local:80";
    set $upstream_backend "http://gateway.hirefy.svc.cluster.local:8081";
    
    location / {
        proxy_pass $upstream_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api {
        proxy_pass $upstream_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    include includes/location_common.conf;
}