
import { ScanFace } from 'lucide-react';
import { useState, useRef } from 'react'

export function OTPpage(){
    const [otp, setOtp] = useState(new Array(6).fill(""));
    const [otpError, setOtpError] = useState(null);
    const otpBoxReference = useRef([]);
    interface props{
        val:string;
        setValue:any;
    }

    function handleChange(value:any, index:any) {
        let newArr = [...otp];
        newArr[index] = value;
        setOtp(newArr);
    
        if(value && index < 6 - 1){
          otpBoxReference.current[index + 1].focus()
        }
      }
    const InputsField = () => {
        return (
            <div>
                {otp.map((digit, index)=>(
                    <input key={index} value={digit} maxLength={1}  
                    onChange={(e)=> handleChange(e.target.value, index)}
                    // ref={(reference) => (otpBoxReference.current[index] = reference)}
                    className='h-8 w-8 md:h-12 md:w-12 text-xl font-bold text-black hover:shadow-lg focus:outline-[#5F88B8]
                        bg-gray-100 border rounded-lg text-center'
                    />
                ))}
            </div>
            // <input
            //     onChange={(e) => setValue(e.target.value)} 
            //     value={val} 
            //     type="text"  
            //     maxLength={1} 
            //     required 
            //     autoComplete='one-time-code'
            //     className='h-8 w-8 md:h-12 md:w-12 text-xl font-bold text-black hover:shadow-lg focus:outline-[#5F88B8]
            //                bg-gray-100 border rounded-lg text-center'
            // />
        );
    }
    const OTP = () => {
        return(
            <div className="flex flex-col gap-4 md:gap-8 items-center justify-center">
                <ScanFace  className='h-8 w-8  md:h-16 md:w-16  text-[#8a8888c5] group-hover:text-[#00adef]'/>
                <div className='flex flex-col gap-1 items-center '>
                    <h1 className='font-bold text-black text-lg md:text-xl'>Authentication</h1>
                    <h1 className='font-light text-black text-xs md:text-sm text-justify'>Enter the code generated by your Authentication App</h1>
                </div>
                <form action="/" method="" className=' flex flex-col gap-4 md:gap-10'>
                    <div className='Inputs flex gap-1 w-full items-center'>
                        <InputsField />
        
                    </div>
                    <div className='flex flex-col gap-2 items-center text-justify'>
                        <button type='submit' className='w-full h-10 md:h-12 bg-[#00adef] text-sm md:text-lg 
                            rounded-lg font-extrabold text-black p-2'>
                            Verify account
                        </button>
                        <h1 className='font-light text-black text-sm md:text-lg'>
                            Didn't get the code?
                            <a href='#' className='text-black font-bold text-sm md:text-lg underline cursor-pointer'>
                                Resent code
                            </a>
                        </h1>
                    </div>
                    
                </form>
            </div>
        );
    }
  
    
    return(
        <div className={`p-4 py-10 flex overflow-hidden maincard group m-auto`}>
            {<OTP />}
        </div>
        
    );
}