
import { ScanFace } from 'lucide-react';
import { useState } from 'react'

export function OTPpage(){
    const [value1, setValue1] = useState("");
    const [value2, setValue2] = useState("");
    const [value3, setValue3] = useState("");
    const [value4, setValue4] = useState("");
    const [value5, setValue5] = useState("");
    const [value6, setValue6] = useState("");
    interface props{
        val:string;
        setValue:any;
    }

    const InputField = ({val, setValue}: props) => {
        return (
            <input
                onChange={(e) => setValue(e.target.value)} 
                value={val} 
                type="text"  
                maxLength={1} 
                required 
                autoComplete='one-time-code'
                className='h-8 w-8 md:h-12 md:w-12 text-xl font-bold text-black hover:shadow-lg focus:outline-[#5F88B8]
                           bg-gray-100 border rounded-lg text-center'
            />
        );
    }
    const OTP = () => {
        return(
            <div className="flex flex-col gap-4 md:gap-8 items-center justify-center">
                <ScanFace  className='h-8 w-8  md:h-16 md:w-16  text-[#8a8888c5] group-hover:text-[#00adef]'/>
                <div className='flex flex-col gap-1 items-center '>
                    <h1 className='font-bold text-black text-lg md:text-xl'>Authentication</h1>
                    <h1 className='font-light text-black text-xs md:text-sm text-justify'>Enter the code generated by your Authentication App</h1>
                </div>
                <form action="/" method="" className=' flex flex-col gap-4 md:gap-10'>
                    <div className='Inputs flex gap-1 w-full items-center'>
                        <InputField val={value1} setValue={setValue1}/>
                        <InputField val={value2} setValue={setValue2}/>
                        <InputField val={value3} setValue={setValue3}/>
                        <InputField val={value4} setValue={setValue4}/>
                        <InputField val={value5} setValue={setValue5}/>
                        <InputField val={value6} setValue={setValue6}/>
                    </div>
                    <div className='flex flex-col gap-2 items-center text-justify'>
                        <button type='submit' className='w-full h-10 md:h-12 bg-[#00adef] text-sm md:text-lg 
                            rounded-lg font-extrabold text-black p-2'>
                            Verify account
                        </button>
                        <h1 className='font-light text-black text-sm md:text-lg'>
                            Didn't get the code?
                            <a href='#' className='text-black font-bold text-sm md:text-lg underline cursor-pointer'>
                                Resent code
                            </a>
                        </h1>
                    </div>
                    
                </form>
            </div>
        );
    }
  
    
    return(
        <div className={`p-4 py-10 flex overflow-hidden maincard group m-auto`}>
            {<OTP />}
        </div>
        
    );
}