import { ScanFace, ArrowRightToLine } from 'lucide-react';
import { useState, useRef, ChangeEvent, KeyboardEvent } from 'react';

export function QRcode() {

    const [otp, setOtp] = useState<string[]>(new Array(6).fill(""));

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        const finalCode = otp.join("");
        console.log("Submitted OTP:", finalCode);
    };

    const QrImage = () =>{
        return (
            <div className='relative flex items-center justify-center  p-2'>
                <img src="/icons/qr.png" alt="" 
                    className='h-28 w-28 '/>
                
                <div className='absolute -top-2 -left-2 border-l-2 border-t-2 rounded-sm w-5 h-5 border-sky-500'></div>
                <div className='absolute -top-2 -right-2 border-r-2 border-t-2 rounded-sm w-5 h-5 border-sky-500'></div>
                <div className='absolute -bottom-2 -left-2 border-l-2 border-b-2 rounded-sm w-5 h-5 border-sky-500'></div>
                <div className='absolute -bottom-2 -right-2 border-r-2 border-b-2 rounded-sm w-5 h-5 border-sky-500'></div>
            </div>
        );
    }

    return (
        <div className="p-4 py-10 flex overflow-hidden group m-auto justify-center maincard">
            <div className="flex flex-col gap-4 md:gap-8 items-center justify-center">
                
                <div className="flex flex-col gap-1 items-center">
                    <h1 className="font-bold text-black text-lg md:text-xl">Authentication</h1>
                    <p className="font-light text-black text-xs md:text-sm text-center">
                        Enter the code generated by your Authentication App
                    </p>
                </div>
                <QrImage />

                <form onSubmit={handleSubmit} className="flex flex-col gap-4 md:gap-10">


                    <div className="flex flex-col gap-2 items-center">
                        <button 
                            type="submit" 
                            className="group flex gap-2 justify-center items-center w-full h-10 md:h-12 bg-[#00adef] text-sm md:text-lg 
                                     rounded-lg font-extrabold text-white p-2  transition-colors"
                        >
                            <p>Next</p>
                            <ArrowRightToLine className='w-5 h-5 group-hover:text-green-400'/>
                        </button>
                        <p className="font-light text-black text-sm md:text-lg">
                            Didn't get the code?{' '}
                            <button type="button" className="text-black font-bold underline cursor-pointer">
                                Reset QR
                            </button>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    );
}