sonar.organization=ibrahimesseddyq
sonar.projectKey=ibrahimesseddyq_main-service
sonar.projectName=main-service

sonar.sources=.
sonar.exclusions=**/vendor/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
